# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v5
        with:
          version: 1.39.17
          actions-cache-folder: 'emsdk-cache'
      - run: npm install
      - run: npx gulp init
      - run: npx gulp runTests  

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v5
        with:
          version: 1.39.17
          actions-cache-folder: 'emsdk-cache'
      - run: npm install
      - run: npx gulp init
      - run: npx gulp release
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
